const hsk1Vocabulary = {
    level1: [
        { chinese: '你', pinyin: 'nǐ', translation: 'you', exampleSentence: '你好', exampleSentencePinyin: 'nǐ hǎo', exampleTranslation: 'Hello' },
        { chinese: '好', pinyin: 'hǎo', translation: 'good', exampleSentence: '很好', exampleSentencePinyin: 'hen3 hao3', exampleTranslation: 'very good' },
        { chinese: '我', pinyin: 'wǒ', translation: 'I/me', exampleSentence: '我好', exampleSentencePinyin: 'wǒ hǎo', exampleTranslation: 'I am well' },
        { chinese: '是', pinyin: 'shì', translation: 'to be', exampleSentence: '我是学生', exampleSentencePinyin: 'wǒ shì xuéshēng', exampleTranslation: 'I am a student' },
        { chinese: '的', pinyin: 'de', translation: 'possessive particle', exampleSentence: '我的书', exampleSentencePinyin: 'wǒ de shū', exampleTranslation: 'my book' },
        { chinese: '一', pinyin: 'yī', translation: 'one', exampleSentence: '一个', exampleSentencePinyin: 'yī ge', exampleTranslation: 'one (classifier)' },
        { chinese: '个', pinyin: 'ge', translation: 'classifier', exampleSentence: '一个人', exampleSentencePinyin: 'yī ge rén', exampleTranslation: 'one person' },
        { chinese: '人', pinyin: 'rén', translation: 'person', exampleSentence: '一个人', exampleSentencePinyin: 'yī ge rén', exampleTranslation: 'one person' },
        { chinese: '在', pinyin: 'zài', translation: 'at/in', exampleSentence: '我在家', exampleSentencePinyin: 'wǒ zài jiā', exampleTranslation: 'I am at home' },
        { chinese: '了', pinyin: 'le', translation: 'particle (completion)', exampleSentence: '做完了', exampleSentencePinyin: 'zuò wán le', exampleTranslation: 'finished' },
        { chinese: '有', pinyin: 'yǒu', translation: 'to have', exampleSentence: '我有书', exampleSentencePinyin: 'wǒ yǒu shū', exampleTranslation: 'I have a book' },
        { chinese: '和', pinyin: 'hé', translation: 'and', exampleSentence: '你和我', exampleSentencePinyin: 'nǐ hé wǒ', exampleTranslation: 'you and me' },
        { chinese: '不', pinyin: 'bù', translation: 'not', exampleSentence: '不好', exampleSentencePinyin: 'bù hǎo', exampleTranslation: 'not good' },
        { chinese: '对', pinyin: 'duì', translation: 'correct', exampleSentence: '对不对', exampleSentencePinyin: 'duì bu duì', exampleTranslation: 'Is it correct?' },
        { chinese: '这', pinyin: 'zhè', translation: 'this', exampleSentence: '这个', exampleSentencePinyin: 'zhè ge', exampleTranslation: 'this one' }
    ],
    level2: [
        { chinese: '那', pinyin: 'nà', translation: 'that', exampleSentence: '那个', exampleSentencePinyin: 'nà ge', exampleTranslation: 'that one' },
        { chinese: '什么', pinyin: 'shénme', translation: 'what', exampleSentence: '什么？', exampleSentencePinyin: 'shénme?', exampleTranslation: 'What?' },
        { chinese: '谁', pinyin: 'shéi', translation: 'who', exampleSentence: '你是谁', exampleSentencePinyin: 'nǐ shì shéi', exampleTranslation: 'Who are you?' },
        { chinese: '哪', pinyin: 'nǎ', translation: 'which', exampleSentence: '哪个', exampleSentencePinyin: 'nǎ ge', exampleTranslation: 'which one' },
        { chinese: '多少', pinyin: 'duōshao', translation: 'how much/many', exampleSentence: '多少钱', exampleSentencePinyin: 'duōshao qián', exampleTranslation: 'how much money' },
        { chinese: '名字', pinyin: 'míngzi', translation: 'name', exampleSentence: '你的名字', exampleSentencePinyin: 'nǐ de míngzi', exampleTranslation: 'your name' },
        { chinese: '学生', pinyin: 'xuésheng', translation: 'student', exampleSentence: '我是学生', exampleSentencePinyin: 'wǒ shì xuéshēng', exampleTranslation: 'I am a student' },
        { chinese: '老师', pinyin: 'lǎoshī', translation: 'teacher', exampleSentence: '他是老师', exampleSentencePinyin: 'tā shì lǎoshī', exampleTranslation: 'He is a teacher' },
        { chinese: '妈妈', pinyin: 'māma', translation: 'mother', exampleSentence: '我的妈妈', exampleSentencePinyin: 'wǒ de māma', exampleTranslation: 'my mother' },
        { chinese: '爸爸', pinyin: 'bàba', translation: 'father', exampleSentence: '我的爸爸', exampleSentencePinyin: 'wǒ de bàba', exampleTranslation: 'my father' },
        { chinese: '朋友', pinyin: 'péngyou', translation: 'friend', exampleSentence: '我的朋友', exampleSentencePinyin: 'wǒ de péngyou', exampleTranslation: 'my friend' },
        { chinese: '书', pinyin: 'shū', translation: 'book', exampleSentence: '我的书', exampleSentencePinyin: 'wǒ de shū', exampleTranslation: 'my book' },
        { chinese: '笔', pinyin: 'bǐ', translation: 'pen', exampleSentence: '一支笔', exampleSentencePinyin: 'yī zhī bǐ', exampleTranslation: 'one pen' },
        { chinese: '桌子', pinyin: 'zhuōzi', translation: 'table', exampleSentence: '在桌子上', exampleSentencePinyin: 'zài zhuōzi shang', exampleTranslation: 'on the table' },
        { chinese: '椅子', pinyin: 'yǐzi', translation: 'chair', exampleSentence: '坐在椅子上', exampleSentencePinyin: 'zuò zài yǐzi shang', exampleTranslation: 'sitting on a chair' }
    ],
    level3: [
        { chinese: '家', pinyin: 'jiā', translation: 'home', exampleSentence: '我在家', exampleSentencePinyin: 'wǒ zài jiā', exampleTranslation: 'I am at home' },
        { chinese: '学校', pinyin: 'xuéxiào', translation: 'school', exampleSentence: '在学校', exampleSentencePinyin: 'zài xuéxiào', exampleTranslation: 'at school' },
        { chinese: '工作', pinyin: 'gōngzuò', translation: 'work', exampleSentence: '我的工作', exampleSentencePinyin: 'wǒ de gōngzuò', exampleTranslation: 'my work' },
        { chinese: '医生', pinyin: 'yīshēng', translation: 'doctor', exampleSentence: '他是医生', exampleSentencePinyin: 'tā shì yīshēng', exampleTranslation: 'He is a doctor' },
        { chinese: '日期', pinyin: 'rìqī', translation: 'date', exampleSentence: '什么日期', exampleSentencePinyin: 'shénme rìqī', exampleTranslation: 'What date?' },
        { chinese: '时间', pinyin: 'shíjiān', translation: 'time', exampleSentence: '现在的时间', exampleSentencePinyin: 'xiànzài de shíjiān', exampleTranslation: 'the current time' },
        { chinese: '今天', pinyin: 'jīntiān', translation: 'today', exampleSentence: '今天天气很好', exampleSentencePinyin: 'jīntiān tiānqì hen hǎo', exampleTranslation: 'Today the weather is nice' },
        { chinese: '昨天', pinyin: 'zuótiān', translation: 'yesterday', exampleSentence: '昨天', exampleSentencePinyin: 'zuótiān', exampleTranslation: 'yesterday' },
        { chinese: '明天', pinyin: 'míngtiān', translation: 'tomorrow', exampleSentence: '明天见', exampleSentencePinyin: 'míngtiān jiàn', exampleTranslation: 'See you tomorrow' },
        { chinese: '早上', pinyin: 'zǎoshang', translation: 'morning', exampleSentence: '早上好', exampleSentencePinyin: 'zǎoshang hǎo', exampleTranslation: 'Good morning' },
        { chinese: '中午', pinyin: 'zhōngwǔ', translation: 'noon', exampleSentence: '中午吃饭', exampleSentencePinyin: 'zhōngwǔ chīfàn', exampleTranslation: 'eat lunch at noon' },
        { chinese: '晚上', pinyin: 'wǎnshang', translation: 'evening', exampleSentence: '晚上好', exampleSentencePinyin: 'wǎnshang hǎo', exampleTranslation: 'Good evening' },
        { chinese: '现在', pinyin: 'xiànzài', translation: 'now', exampleSentence: '现在怎样', exampleSentencePinyin: 'xiànzài zenyàng', exampleTranslation: 'How is it now?' },
        { chinese: '吃', pinyin: 'chī', translation: 'to eat', exampleSentence: '吃饭', exampleSentencePinyin: 'chīfàn', exampleTranslation: 'eat rice / have a meal' },
        { chinese: '喝', pinyin: 'hē', translation: 'to drink', exampleSentence: '喝水', exampleSentencePinyin: 'hē shuǐ', exampleTranslation: 'drink water' }
    ],
    level4: [
        { chinese: '睡', pinyin: 'shuì', translation: 'to sleep', exampleSentence: '去睡觉', exampleSentencePinyin: 'qù shuìjiào', exampleTranslation: 'go to sleep' },
        { chinese: '走', pinyin: 'zǒu', translation: 'to walk / to go', exampleSentence: '走路', exampleSentencePinyin: 'zǒu lù', exampleTranslation: 'walk' },
        { chinese: '来', pinyin: 'lái', translation: 'to come', exampleSentence: '来中国', exampleSentencePinyin: 'lái Zhōngguó', exampleTranslation: 'come to China' },
        { chinese: '去', pinyin: 'qù', translation: 'to go', exampleSentence: '去学校', exampleSentencePinyin: 'qù xuéxiào', exampleTranslation: 'go to school' },
        { chinese: '看', pinyin: 'kàn', translation: 'to look / to watch', exampleSentence: '看电视', exampleSentencePinyin: 'kàn diànshì', exampleTranslation: 'watch TV' },
        { chinese: '听', pinyin: 'tīng', translation: 'to listen', exampleSentence: '听音乐', exampleSentencePinyin: 'tīng yīnyuè', exampleTranslation: 'listen to music' },
        { chinese: '说', pinyin: 'shuō', translation: 'to speak / to say', exampleSentence: '说话', exampleSentencePinyin: 'shuōhuà', exampleTranslation: 'speak / talk' },
        { chinese: '读', pinyin: 'dú', translation: 'to read', exampleSentence: '读书', exampleSentencePinyin: 'dúshū', exampleTranslation: 'read books' },
        { chinese: '写', pinyin: 'xiě', translation: 'to write', exampleSentence: '写字', exampleSentencePinyin: 'xiězì', exampleTranslation: 'write characters' },
        { chinese: '做', pinyin: 'zuò', translation: 'to do / to make', exampleSentence: '做功课', exampleSentencePinyin: 'zuò gōngkè', exampleTranslation: 'do homework' },
        { chinese: '玩', pinyin: 'wán', translation: 'to play', exampleSentence: '玩游戏', exampleSentencePinyin: 'wán yóuxì', exampleTranslation: 'play games' },
        { chinese: '学', pinyin: 'xué', translation: 'to study / to learn', exampleSentence: '学中文', exampleSentencePinyin: 'xué Zhōngwén', exampleTranslation: 'study Chinese' },
        { chinese: '教', pinyin: 'jiāo', translation: 'to teach', exampleSentence: '教学生', exampleSentencePinyin: 'jiāo xuéshēng', exampleTranslation: 'teach students' },
        { chinese: '买', pinyin: 'mǎi', translation: 'to buy', exampleSentence: '买书', exampleSentencePinyin: 'mǎi shū', exampleTranslation: 'buy books' },
        { chinese: '卖', pinyin: 'mài', translation: 'to sell', exampleSentence: '卖东西', exampleSentencePinyin: 'mài dōngxi', exampleTranslation: 'sell things' }
    ],
    level5: [
        { chinese: '找', pinyin: 'zhǎo', translation: 'to find / to look for', exampleSentence: '找钱', exampleSentencePinyin: 'zhǎo qián', exampleTranslation: 'give change / find money' },
        { chinese: '给', pinyin: 'gěi', translation: 'to give', exampleSentence: '给我', exampleSentencePinyin: 'gěi wǒ', exampleTranslation: 'give me' },
        { chinese: '爱', pinyin: 'ài', translation: 'to love', exampleSentence: '爱你', exampleSentencePinyin: 'ài nǐ', exampleTranslation: 'love you' },
        { chinese: '开', pinyin: 'kāi', translation: 'to open', exampleSentence: '开门', exampleSentencePinyin: 'kāi mén', exampleTranslation: 'open the door' },
        { chinese: '关', pinyin: 'guān', translation: 'to close', exampleSentence: '关门', exampleSentencePinyin: 'guān mén', exampleTranslation: 'close the door' },
        { chinese: '坐', pinyin: 'zuò', translation: 'to sit', exampleSentence: '坐下', exampleSentencePinyin: 'zuò xia', exampleTranslation: 'sit down' },
        { chinese: '站', pinyin: 'zhàn', translation: 'to stand', exampleSentence: '站起来', exampleSentencePinyin: 'zhàn qǐlai', exampleTranslation: 'stand up' },
        { chinese: '跑', pinyin: 'pǎo', translation: 'to run', exampleSentence: '跑步', exampleSentencePinyin: 'pǎo bù', exampleTranslation: 'run / jog' },
        { chinese: '会', pinyin: 'huì', translation: 'can / to be able to', exampleSentence: '你会吗', exampleSentencePinyin: 'nǐ huì ma', exampleTranslation: 'Can you?' },
        { chinese: '能', pinyin: 'néng', translation: 'can / able', exampleSentence: '你能做吗', exampleSentencePinyin: 'nǐ néng zuò ma', exampleTranslation: 'Can you do it?' },
        { chinese: '想', pinyin: 'xiǎng', translation: 'to want / to think', exampleSentence: '我想去', exampleSentencePinyin: 'wǒ xiǎng qù', exampleTranslation: 'I want to go' },
        { chinese: '应该', pinyin: 'yīnggāi', translation: 'should', exampleSentence: '应该去', exampleSentencePinyin: 'yīnggāi qù', exampleTranslation: 'should go' },
        { chinese: '可以', pinyin: 'kěyǐ', translation: 'can / may', exampleSentence: '可以吗', exampleSentencePinyin: 'kěyǐ ma', exampleTranslation: 'Is it okay?' },
        { chinese: '新', pinyin: 'xīn', translation: 'new', exampleSentence: '新书', exampleSentencePinyin: 'xīn shū', exampleTranslation: 'new book' },
        { chinese: '旧', pinyin: 'jiù', translation: 'old', exampleSentence: '旧书', exampleSentencePinyin: 'jiù shū', exampleTranslation: 'old book' }
    ],
    level6: [
        { chinese: '大', pinyin: 'dà', translation: 'big / large', exampleSentence: '大房子', exampleSentencePinyin: 'dà fángzi', exampleTranslation: 'big house' },
        { chinese: '小', pinyin: 'xiǎo', translation: 'small', exampleSentence: '小房子', exampleSentencePinyin: 'xiǎo fángzi', exampleTranslation: 'small house' },
        { chinese: '多', pinyin: 'duō', translation: 'many / much', exampleSentence: '很多', exampleSentencePinyin: 'hen duō', exampleTranslation: 'a lot / very much' },
        { chinese: '少', pinyin: 'shǎo', translation: 'few / little', exampleSentence: '很少', exampleSentencePinyin: 'hen shǎo', exampleTranslation: 'very little' },
        { chinese: '长', pinyin: 'cháng', translation: 'long', exampleSentence: '很长', exampleSentencePinyin: 'hen cháng', exampleTranslation: 'very long' },
        { chinese: '短', pinyin: 'duǎn', translation: 'short', exampleSentence: '很短', exampleSentencePinyin: 'hen duǎn', exampleTranslation: 'very short' },
        { chinese: '高', pinyin: 'gāo', translation: 'tall / high', exampleSentence: '很高', exampleSentencePinyin: 'hen gāo', exampleTranslation: 'very tall' },
        { chinese: '矮', pinyin: 'ǎi', translation: 'short (height)', exampleSentence: '很矮', exampleSentencePinyin: 'hen ǎi', exampleTranslation: 'very short' },
        { chinese: '漂亮', pinyin: 'piàoliang', translation: 'beautiful', exampleSentence: '很漂亮', exampleSentencePinyin: 'hen piàoliang', exampleTranslation: 'very beautiful' },
        { chinese: '聪明', pinyin: 'cōngming', translation: 'clever / intelligent', exampleSentence: '很聪明', exampleSentencePinyin: 'hen cōngming', exampleTranslation: 'very intelligent' },
        { chinese: '年', pinyin: 'nián', translation: 'year', exampleSentence: '今年', exampleSentencePinyin: 'jīnnián', exampleTranslation: 'this year' },
        { chinese: '月', pinyin: 'yuè', translation: 'month', exampleSentence: '一月', exampleSentencePinyin: 'yī yuè', exampleTranslation: 'January' },
        { chinese: '天', pinyin: 'tiān', translation: 'day / sky', exampleSentence: '一天', exampleSentencePinyin: 'yī tiān', exampleTranslation: 'one day' },
        { chinese: '号', pinyin: 'hào', translation: 'number / date', exampleSentence: '几号', exampleSentencePinyin: 'jǐ hào', exampleTranslation: 'what date' },
        { chinese: '星期', pinyin: 'xīngqī', translation: 'week', exampleSentence: '星期一', exampleSentencePinyin: 'xīngqī yī', exampleTranslation: 'Monday' }
    ],
    level7: [
        { chinese: '钟', pinyin: 'zhōng', translation: 'o\'clock', exampleSentence: '一点钟', exampleSentencePinyin: 'yī diǎn zhōng', exampleTranslation: 'one o\'clock' },
        { chinese: '红', pinyin: 'hóng', translation: 'red', exampleSentence: '红色', exampleSentencePinyin: 'hóng sè', exampleTranslation: 'red color' },
        { chinese: '蓝', pinyin: 'lán', translation: 'blue', exampleSentence: '蓝色', exampleSentencePinyin: 'lán sè', exampleTranslation: 'blue color' },
        { chinese: '黄', pinyin: 'huáng', translation: 'yellow', exampleSentence: '黄色', exampleSentencePinyin: 'huáng sè', exampleTranslation: 'yellow color' },
        { chinese: '白', pinyin: 'bái', translation: 'white', exampleSentence: '白色', exampleSentencePinyin: 'bái sè', exampleTranslation: 'white color' },
        { chinese: '黑', pinyin: 'hēi', translation: 'black', exampleSentence: '黑色', exampleSentencePinyin: 'hēi sè', exampleTranslation: 'black color' },
        { chinese: '绿', pinyin: 'lǜ', translation: 'green', exampleSentence: '绿色', exampleSentencePinyin: 'lǜ sè', exampleTranslation: 'green color' },
        { chinese: '吗', pinyin: 'ma', translation: 'question particle', exampleSentence: '你好吗', exampleSentencePinyin: 'nǐ hǎo ma', exampleTranslation: 'How are you?' },
        { chinese: '呢', pinyin: 'ne', translation: 'question particle', exampleSentence: '你呢', exampleSentencePinyin: 'nǐ ne', exampleTranslation: 'And you?' },
        { chinese: '吧', pinyin: 'ba', translation: 'particle (suggestion)', exampleSentence: '走吧', exampleSentencePinyin: 'zǒu ba', exampleTranslation: 'Let\'s go' },
        { chinese: '也', pinyin: 'yě', translation: 'also / too', exampleSentence: '我也去', exampleSentencePinyin: 'wǒ yě qù', exampleTranslation: 'I\'ll go too' },
        { chinese: '都', pinyin: 'dōu', translation: 'all / both', exampleSentence: '都好', exampleSentencePinyin: 'dōu hǎo', exampleTranslation: 'all are fine' },
        { chinese: '只', pinyin: 'zhǐ', translation: 'only', exampleSentence: '只有一个', exampleSentencePinyin: 'zhǐ yǒu yī ge', exampleTranslation: 'only one' },
        { chinese: '很', pinyin: 'hěn', translation: 'very', exampleSentence: '很好', exampleSentencePinyin: 'hen hǎo', exampleTranslation: 'very good' },
        { chinese: '太', pinyin: 'tài', translation: 'too', exampleSentence: '太好了', exampleSentencePinyin: 'tai hǎo le', exampleTranslation: 'too good / great' }
    ],
    level8: [
        { chinese: '非常', pinyin: 'fēicháng', translation: 'extremely', exampleSentence: '非常好', exampleSentencePinyin: 'fēicháng hǎo', exampleTranslation: 'extremely good' },
        { chinese: '完全', pinyin: 'wánquán', translation: 'completely', exampleSentence: '完全不同', exampleSentencePinyin: 'wánquán bu tóng', exampleTranslation: 'completely different' },
        { chinese: '差不多', pinyin: 'chàbuduō', translation: 'almost / about the same', exampleSentence: '差不多了', exampleSentencePinyin: 'chàbuduō le', exampleTranslation: 'almost done' },
        { chinese: '再', pinyin: 'zài', translation: 'again', exampleSentence: '再来一次', exampleSentencePinyin: 'zài lai yī ci', exampleTranslation: 'one more time' },
        { chinese: '就', pinyin: 'jiù', translation: 'then / just', exampleSentence: '我就来', exampleSentencePinyin: 'wǒ jiu lai', exampleTranslation: 'I\'ll be right there' },
        { chinese: '才', pinyin: 'cái', translation: 'only then', exampleSentence: '才来', exampleSentencePinyin: 'cai lai', exampleTranslation: 'just arrived' },
        { chinese: '要', pinyin: 'yào', translation: 'want / need / will', exampleSentence: '我要去', exampleSentencePinyin: 'wǒ yào qù', exampleTranslation: 'I want to go' },
        { chinese: '得', pinyin: 'dei', translation: 'must / have to', exampleSentence: '必须得去', exampleSentencePinyin: 'bìxu dei qu', exampleTranslation: 'must go' },
        { chinese: '水', pinyin: 'shuǐ', translation: 'water', exampleSentence: '喝水', exampleSentencePinyin: 'hē shuǐ', exampleTranslation: 'drink water' },
        { chinese: '火', pinyin: 'huǒ', translation: 'fire', exampleSentence: '生火', exampleSentencePinyin: 'shēng huǒ', exampleTranslation: 'make a fire' },
        { chinese: '山', pinyin: 'shān', translation: 'mountain', exampleSentence: '爬山', exampleSentencePinyin: 'pá shān', exampleTranslation: 'climb a mountain' },
        { chinese: '中国', pinyin: 'Zhōngguó', translation: 'China', exampleSentence: '来自中国', exampleSentencePinyin: 'lái zi Zhōngguó', exampleTranslation: 'from China' },
        { chinese: '英国', pinyin: 'Yīngguó', translation: 'England / UK', exampleSentence: '来自英国', exampleSentencePinyin: 'lái zi Yīngguó', exampleTranslation: 'from England' },
        { chinese: '美国', pinyin: 'Měiguó', translation: 'USA', exampleSentence: '来自美国', exampleSentencePinyin: 'lái zi Měiguó', exampleTranslation: 'from USA' },
        { chinese: '钱', pinyin: 'qián', translation: 'money', exampleSentence: '多少钱', exampleSentencePinyin: 'duōshao qián', exampleTranslation: 'how much money' }
    ],
    level9: [
        { chinese: '块', pinyin: 'kuài', translation: 'yuan (currency)', exampleSentence: '十块钱', exampleSentencePinyin: 'shi kuài qián', exampleTranslation: 'ten yuan' },
        { chinese: '分', pinyin: 'fēn', translation: 'cent / minute', exampleSentence: '五分钟', exampleSentencePinyin: 'wu fen zhong', exampleTranslation: 'five minutes' },
        { chinese: '号', pinyin: 'hào', translation: 'number', exampleSentence: '电话号码', exampleSentencePinyin: 'diànhuà haoma', exampleTranslation: 'phone number' },
        { chinese: '电话', pinyin: 'diànhuà', translation: 'telephone', exampleSentence: '打电话', exampleSentencePinyin: 'da diànhuà', exampleTranslation: 'make a phone call' },
        { chinese: '米', pinyin: 'mǐ', translation: 'meter', exampleSentence: '一米', exampleSentencePinyin: 'yī mǐ', exampleTranslation: 'one meter' },
        { chinese: '公里', pinyin: 'gōnglǐ', translation: 'kilometer', exampleSentence: '十公里', exampleSentencePinyin: 'shi gōnglǐ', exampleTranslation: 'ten kilometers' },
        { chinese: '克', pinyin: 'kè', translation: 'gram', exampleSentence: '一克', exampleSentencePinyin: 'yī kè', exampleTranslation: 'one gram' },
        { chinese: '斤', pinyin: 'jīn', translation: 'catty (weight)', exampleSentence: '一斤', exampleSentencePinyin: 'yī jīn', exampleTranslation: 'one catty' },
        { chinese: '去年', pinyin: 'qùnián', translation: 'last year', exampleSentence: '去年的事', exampleSentencePinyin: 'qùnián de shi', exampleTranslation: 'last year\'s matter' },
        { chinese: '明年', pinyin: 'míng nián', translation: 'next year', exampleSentence: '明年见', exampleSentencePinyin: 'míng nián jiàn', exampleTranslation: 'see you next year' },
        { chinese: '下月', pinyin: 'xià yuè', translation: 'next month', exampleSentence: '下月见', exampleSentencePinyin: 'xià yuè jiàn', exampleTranslation: 'see you next month' },
        { chinese: '上午', pinyin: 'shàngwǔ', translation: 'morning', exampleSentence: '上午好', exampleSentencePinyin: 'shàngwǔ hǎo', exampleTranslation: 'good morning' },
        { chinese: '下午', pinyin: 'xiàwǔ', translation: 'afternoon', exampleSentence: '下午好', exampleSentencePinyin: 'xiàwǔ hǎo', exampleTranslation: 'good afternoon' },
        { chinese: '夜晚', pinyin: 'yèwǎn', translation: 'night', exampleSentence: '夜晚好', exampleSentencePinyin: 'yèwǎn hǎo', exampleTranslation: 'good night' },
        { chinese: '一点', pinyin: 'yī diǎn', translation: 'one o\'clock', exampleSentence: '一点见', exampleSentencePinyin: 'yī diǎn jiàn', exampleTranslation: 'see you at one' }
    ],
    level10: [
        { chinese: '两点', pinyin: 'liǎng diǎn', translation: 'two o\'clock', exampleSentence: '两点见', exampleSentencePinyin: 'liǎng diǎn jiàn', exampleTranslation: 'see you at two' },
        { chinese: '三点', pinyin: 'sān diǎn', translation: 'three o\'clock', exampleSentence: '三点见', exampleSentencePinyin: 'sān diǎn jiàn', exampleTranslation: 'see you at three' },
        { chinese: '四点', pinyin: 'sì diǎn', translation: 'four o\'clock', exampleSentence: '四点见', exampleSentencePinyin: 'sì diǎn jiàn', exampleTranslation: 'see you at four' },
        { chinese: '五点', pinyin: 'wǔ diǎn', translation: 'five o\'clock', exampleSentence: '五点见', exampleSentencePinyin: 'wǔ diǎn jiàn', exampleTranslation: 'see you at five' },
        { chinese: '六点', pinyin: 'liù diǎn', translation: 'six o\'clock', exampleSentence: '六点见', exampleSentencePinyin: 'liù diǎn jiàn', exampleTranslation: 'see you at six' },
        { chinese: '七点', pinyin: 'qī diǎn', translation: 'seven o\'clock', exampleSentence: '七点见', exampleSentencePinyin: 'qī diǎn jiàn', exampleTranslation: 'see you at seven' },
        { chinese: '八点', pinyin: 'bā diǎn', translation: 'eight o\'clock', exampleSentence: '八点见', exampleSentencePinyin: 'bā diǎn jiàn', exampleTranslation: 'see you at eight' },
        { chinese: '九点', pinyin: 'jiǔ diǎn', translation: 'nine o\'clock', exampleSentence: '九点见', exampleSentencePinyin: 'jiǔ diǎn jiàn', exampleTranslation: 'see you at nine' },
        { chinese: '十点', pinyin: 'shí diǎn', translation: 'ten o\'clock', exampleSentence: '十点见', exampleSentencePinyin: 'shí diǎn jiàn', exampleTranslation: 'see you at ten' },
        { chinese: '两', pinyin: 'liǎng', translation: 'two', exampleSentence: '两个', exampleSentencePinyin: 'liǎng ge', exampleTranslation: 'two' },
        { chinese: '三', pinyin: 'sān', translation: 'three', exampleSentence: '三个', exampleSentencePinyin: 'sān ge', exampleTranslation: 'three' },
        { chinese: '四', pinyin: 'sì', translation: 'four', exampleSentence: '四个', exampleSentencePinyin: 'sì ge', exampleTranslation: 'four' },
        { chinese: '五', pinyin: 'wǔ', translation: 'five', exampleSentence: '五个', exampleSentencePinyin: 'wǔ ge', exampleTranslation: 'five' },
        { chinese: '十', pinyin: 'shí', translation: 'ten', exampleSentence: '十个', exampleSentencePinyin: 'shí ge', exampleTranslation: 'ten' },
        { chinese: '百', pinyin: 'bǎi', translation: 'hundred', exampleSentence: '一百', exampleSentencePinyin: 'yī bǎi', exampleTranslation: 'one hundred' }
    ]
};
